apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metadata
  template:
    metadata:
      labels:
        app: metadata
    spec:
      containers:
      - name: metadata
        image: zhasofff/metadata:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8081