global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets:
      - host.docker.internal:9093      
rule_files:
- alerts.rules
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:  
    - localhost:9090
  - targets:    
    - host.docker.internal:8091
    labels:
      service: metadata
  - targets:    
    - host.docker.internal:8092
    labels:
      service: rating
  - targets:    
    - host.docker.internal:8093
    labels:
      service: movie